runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# libraries:
# - name: jinja2
#   version: latest
# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:

- url: /blog/js
  static_dir : /templates/blog/js

- url: /blog/css
  static_dir : /templates/blog/css

- url: /blog/scss
  static_dir : /templates/blog/scss

- url: /blog/fonts
  static_dir : /templates/blog/fonts

- url: /blog/images
  static_dir : /templates/blog/images

- url: /login/js
  static_dir : /templates/login/js

- url: /login/css
  static_dir : /templates/login/css

- url: /login/vendor
  static_dir : /templates/login/vendor

- url: /login/fonts
  static_dir : /templates/login/fonts

- url: /login/html
  static_dir : /templates/login/html

- url: /static
  static_dir : /templates/static

- url: /
  script: main.app

- url: /.*
  script: main.app
